/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.demo;

import org.junit.Test;
import static org.junit.Assert.*;

public class DemoApplicationTest {
    @Test public void appHasAGreeting() {
        DemoApplication classUnderTest = new DemoApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
